import { describe, expect, it } from "vitest";
import { GENERATED_MARKER, isGeneratedHtml } from "../../src/core/ownership.js";

describe("isGeneratedHtml", () => {
  it("detects files generated by this package", () => {
    expect(isGeneratedHtml(`<!doctype html>\n${GENERATED_MARKER}\n<title>Project Progress</title>`)).toBe(true);
  });

  it("rejects unrelated html files", () => {
    expect(isGeneratedHtml("<!doctype html><title>Existing docs</title>")).toBe(false);
  });
});
