import { access, readFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { isGeneratedHtml } from "./ownership.js";

export type FileActionKind = "create" | "preserve" | "overwrite" | "conflict";

export type FileAction = {
  kind: FileActionKind;
  path: string;
  relativePath: string;
  reason: string;
};

export type InstallPlan = {
  root: string;
  outputPath: string;
  outputDirectory: string;
  actions: FileAction[];
  hasConflicts: boolean;
};

export type CreateInstallPlanOptions = {
  root: string;
  outputPath: string;
  force: boolean;
};

async function fileExists(path: string) {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

function toRelative(root: string, path: string) {
  return relative(root, path) || ".";
}

export async function createInstallPlan(options: CreateInstallPlanOptions): Promise<InstallPlan> {
  const root = resolve(options.root);
  const outputPath = resolve(options.outputPath);
  const progressPath = resolve(root, "context/progress-tracker.md");
  const milestonePath = resolve(root, "context/milestone-tracker.md");
  const actions: FileAction[] = [];

  for (const trackerPath of [progressPath, milestonePath]) {
    const exists = await fileExists(trackerPath);
    actions.push({
      kind: exists ? "preserve" : "create",
      path: trackerPath,
      relativePath: toRelative(root, trackerPath),
      reason: exists ? "Existing tracker markdown is preserved." : "Tracker markdown is missing and will be created.",
    });
  }

  if (!(await fileExists(outputPath))) {
    actions.push({
      kind: "create",
      path: outputPath,
      relativePath: toRelative(root, outputPath),
      reason: "Static progress dashboard will be created.",
    });
  } else {
    const existingHtml = await readFile(outputPath, "utf8");
    const generated = isGeneratedHtml(existingHtml);
    actions.push({
      kind: generated && options.force ? "overwrite" : generated ? "preserve" : "conflict",
      path: outputPath,
      relativePath: toRelative(root, outputPath),
      reason: generated
        ? options.force
          ? "Existing generated dashboard will be overwritten because --force was passed."
          : "Existing generated dashboard is preserved; pass --force to regenerate it."
        : "Existing HTML does not appear to be generated by this tool.",
    });
  }

  return {
    root,
    outputPath,
    outputDirectory: dirname(outputPath),
    actions,
    hasConflicts: actions.some((action) => action.kind === "conflict"),
  };
}
