export const GENERATED_MARKER = "<!-- Generated by @linhaishe/progress-tracker-site-generator. -->";

export function isGeneratedHtml(content: string) {
  return content.includes(GENERATED_MARKER);
}
